services:
  srcbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${HOST_BIND:-127.0.0.1}:2150:2150'
    volumes:
      - type: bind
        source: ~/.srcbook
        target: /root/.srcbook
        bind:
          create_host_path: true
      - type: bind
        source: ${HOME}/Desktop
        target: /app/data/Desktop
        bind:
          create_host_path: true
      - type: bind
        source: ${HOME}/Downloads
        target: /app/data/Downloads
        bind:
          create_host_path: true
    environment:
      - NODE_ENV=production
      - HOST=${HOST_BIND:-127.0.0.1}
      - SRCBOOK_INSTALL_DEPS=true
    command: ['pnpm', 'start']
